{% set name = "pyiron_contrib" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_contrib-{{ version }}.tar.gz
  sha256: fdfc014a894a061d1fff97c98ccf66a169a495bc77178e142866451c46b20708
  patches:
    - versioneer.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base >=3.8.2
    - numpy >=1.26.3  # for numba compatibility
    - pyiron_base >=0.7.2
    - scipy >=1.12.0
    - seaborn >=0.13.2
    - pyparsing >=3.1.1

test:
  imports:
    - pyiron_contrib
  commands:
    - pip check
  requires:
    - pip
    - boto3

about:
  home: https://github.com/pyiron/pyiron_contrib
  summary: Repository for user-generated plugins to the pyiron IDE.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
    - niklassiemer
