{% set name = "pyiron_contrib" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 649e183983417cae18da6177cfd29824150c3f083a795a23984ffa4f1561b3f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - ase >=3.19.1
    - matplotlib-base >=3.2.1
    - numpy >=1.19.1
    - pyiron >=0.3.6
    - python >=2.7
    - scikit-image >=0.17.2
    - scipy >=1.5.2
    - seaborn >=0.11.0

test:
  imports:
    - pyiron_contrib
    - pyiron_contrib.image
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_contrib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Repository for user-generated plugins to the pyiron IDE.

  description: |
    Repository for user-generated plugins to the pyiron IDE.
  doc_url: https://github.com/pyiron/pyiron_contrib
  dev_url: https://github.com/pyiron/pyiron_contrib

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - muh-hassani
    - niklassiemer
