{% set name = "pyiron_contrib" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8656d9a0bf02d03f84004d17c21514a181ed540159c30b77e900e8fd78937ef4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ase >=3.22.1
    - matplotlib-base >=3.3.4
    - numpy >=1.22.4
    - pyiron >=0.4.3
    - pyiron_atomistics >=0.2.47
    - python >=3.6
    - scikit-image >=0.19.2
    - scipy >=1.8.1
    - seaborn >=0.11.2

test:
  imports:
    - pyiron_contrib
    - pyiron_contrib.image
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_contrib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Repository for user-generated plugins to the pyiron IDE.

  description: |
    Repository for user-generated plugins to the pyiron IDE.
  doc_url: https://github.com/pyiron/pyiron_contrib
  dev_url: https://github.com/pyiron/pyiron_contrib

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - muh-hassani
    - niklassiemer
