{% set name = "pyiron_contrib" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ec4d6a923e36a407cb334e031d2204ce090cce120583fab5691af2e0359402d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ase >=3.21.1
    - matplotlib-base >=3.3.4
    - numpy >=1.16  # >=1.20.1
    - pyiron >=0.4.0
    - pyiron_atomistics >=0.2.5
    - python >=3.6
    - scikit-image >=0.18.1
    - scipy >=1.6.0
    - seaborn >=0.11.1

test:
  imports:
    - pyiron_contrib
    - pyiron_contrib.image
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_contrib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Repository for user-generated plugins to the pyiron IDE.

  description: |
    Repository for user-generated plugins to the pyiron IDE.
  doc_url: https://github.com/pyiron/pyiron_contrib
  dev_url: https://github.com/pyiron/pyiron_contrib

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - muh-hassani
    - niklassiemer
