{% set name = "pyiron_contrib" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_contrib-{{ version }}.tar.gz
  sha256: fd2ad1352eb743ee1464d3ae13c224babf7f250c602768749fb07cddeb5c571f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base >=3.7.2
    - numpy >=1.23.4  # for numba compatibility
    - pyiron_base >=0.6.3
    - scipy >=1.11.1
    - seaborn >=0.12.2
    - pyparsing >=3.0.9

test:
  imports:
    - pyiron_contrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_contrib
  summary: Repository for user-generated plugins to the pyiron IDE.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
    - niklassiemer
