{% set name = "pyiron_contrib" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_contrib-{{ version }}.tar.gz
  sha256: c906c0be2f8d2e180bc358ad4f8e8897f9d878eb3f2300cc6e3b8594af0a98ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base >=3.8.3
    - numpy >=1.26.4  # for numba compatibility
    - pyiron_base >=0.7.9
    - scipy >=1.12.0
    - seaborn >=0.13.2
    - pyparsing >=3.1.2

test:
  imports:
    - pyiron_contrib
  commands:
    - pip check
  requires:
    - pip
    - boto3

about:
  home: https://github.com/pyiron/pyiron_contrib
  summary: Repository for user-generated plugins to the pyiron IDE.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
    - niklassiemer
