{% set name = "pyiron_contrib" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd2ad1352eb743ee1464d3ae13c224babf7f250c602768749fb07cddeb5c571f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ase >=3.22.1
    - matplotlib-base >=3.7.1
    - numpy >=1.19.5  # for numba and pytorch compatibility
    - pyiron_base >=0.6.3
    - pyiron_atomistics >=0.3.0
    - pyparsing =3.0.9
    - python >=3.6
    - scikit-image >=0.21.0
    - scipy >=1.10.1
    - seaborn >=0.12.2
    - pyparsing >=3.0.9
    - pycp2k >=0.2.2
    - moto >=4.1.14
    - randspg >=0.0.1
    - typeguard >=4.1.0
    - aws-sam-translator >=1.71.0
    - boto3 =1.28.15
    - pympipool >=0.6.1
    - distributed =2023.5.0

test:
  imports:
    - pyiron_contrib
    - pyiron_contrib.image
    - pyiron_atomistics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_contrib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Repository for user-generated plugins to the pyiron IDE.

  description: |
    Repository for user-generated plugins to the pyiron IDE.
  doc_url: https://github.com/pyiron/pyiron_contrib
  dev_url: https://github.com/pyiron/pyiron_contrib

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
    - niklassiemer
